/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ProjectsLazyImport = createFileRoute('/projects')()
const ExperienceLazyImport = createFileRoute('/experience')()

// Create/Update Routes

const ProjectsLazyRoute = ProjectsLazyImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/projects.lazy').then((d) => d.Route))

const ExperienceLazyRoute = ExperienceLazyImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/experience.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceLazyImport
      parentRoute: typeof rootRoute
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceLazyRoute
  '/projects': typeof ProjectsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceLazyRoute
  '/projects': typeof ProjectsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/experience': typeof ExperienceLazyRoute
  '/projects': typeof ProjectsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/experience' | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/experience' | '/projects'
  id: '__root__' | '/' | '/experience' | '/projects'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExperienceLazyRoute: typeof ExperienceLazyRoute
  ProjectsLazyRoute: typeof ProjectsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExperienceLazyRoute: ExperienceLazyRoute,
  ProjectsLazyRoute: ProjectsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/experience",
        "/projects"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/experience": {
      "filePath": "experience.lazy.tsx"
    },
    "/projects": {
      "filePath": "projects.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
